spring:
  profiles: release

  datasource:
    username: root
    password: 479803313
    url: jdbc:mysql://127.0.0.1:3306/fish_house?useSSL=false&serverTimezone=Asia/Shanghai


  # 热重启
  devtools:
    restart:
      enabled: false

  redis:
    host: 127.0.0.1
    database: 0
    password: sicau


server:
  port: 8081
  servlet:
    context-path: /houseadmin