spring:
  profiles: dev

  datasource:
    username: root
    password: 479803313
    url: jdbc:mysql://nadev.xyz:3306/fish_house?useSSL=false&serverTimezone=Asia/Shanghai

  # 热重启
  devtools:
    restart:
      enabled: true

  redis:
    host: nadev.xyz
    database: 0
    password: sicau

server:
  port: 8080
